name: GitHub Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout 
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install node_modules/
        run: yarn

      - name: Build Project
        run: yarn build

  deploy:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Deployment
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-project-name: 'github-actions-reactapp'